[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atmosthermo"
version = "0.1.0"
description = "Atmospheric thermodynamics utilities"
readme = "README.md"
authors = [
    { name = "Spencer" }
]
license = { text = "MIT" }
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/SpencerRJones/atmosthermo"
Repository = "https://github.com/SpencerRJones/atmosthermo"
Issues = "https://github.com/SpencerRJones/atmosthermo/issues"

dependencies = [
    "numpy",
    "scipy",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
atmosthermo = ["*.txt"]
